export const GET_BRANDS_START = "GET_BRANDS_START";
export const GET_BRANDS_SUCCESS = "GET_BRANDS_SUCCESS";
export const GET_BRANDS_FAILURE = "GET_BRANDS_FAILURE";

export const GET_BRAND_BY_ID_START = "GET_BRAND_BY_ID_START";
export const GET_BRAND_BY_ID_SUCCESS = "GET_BRAND_BY_ID_SUCCESS";
export const GET_BRAND_BY_ID_FAILURE = "GET_BRAND_BY_ID_FAILURE";

export const GET_FEATURED_BRANDS_START = "GET_FEATURED_BRANDS_START";
export const GET_FEATURED_BRANDS_SUCCESS = "GET_FEATURED_BRANDS_SUCCESS";
export const GET_FEATURED_BRANDS_FAILURE = "GET_FEATURED_BRANDS_FAILURE";

export const CREATE_BRAND_START = "CREATE_BRAND_START";
export const CREATE_BRAND_SUCCESS = "CREATE_BRAND_SUCCESS";
export const CREATE_BRAND_FAILURE = "CREATE_BRAND_FAILURE";

export const UPDATE_BRAND_START = "UPDATE_BRAND_START";
export const UPDATE_BRAND_SUCCESS = "UPDATE_BRAND_SUCCESS";
export const UPDATE_BRAND_FAILURE = "UPDATE_BRAND_FAILURE";

export const DELETE_BRAND_START = "DELETE_BRAND_START";
export const DELETE_BRAND_SUCCESS = "DELETE_BRAND_SUCCESS";
export const DELETE_BRAND_FAILURE = "DELETE_BRAND_FAILURE";
