// Add to cart
export const ADD_TO_CART_REQUEST = "ADD_TO_CART_REQUEST";
export const ADD_TO_CART_SUCCESS = "ADD_TO_CART_SUCCESS";
export const ADD_TO_CART_FAILURE = "ADD_TO_CART_FAILURE";

// Get cart
export const GET_CART_REQUEST = "GET_CART_REQUEST";
export const GET_CART_SUCCESS = "GET_CART_SUCCESS";
export const GET_CART_FAILURE = "GET_CART_FAILURE";

// Update cart item
export const UPDATE_CART_ITEM_REQUEST = "UPDATE_CART_ITEM_REQUEST";
export const UPDATE_CART_ITEM_SUCCESS = "UPDATE_CART_ITEM_SUCCESS";
export const UPDATE_CART_ITEM_FAILURE = "UPDATE_CART_ITEM_FAILURE";

// Remove from cart
export const REMOVE_FROM_CART_REQUEST = "REMOVE_FROM_CART_REQUEST";
export const REMOVE_FROM_CART_SUCCESS = "REMOVE_FROM_CART_SUCCESS";
export const REMOVE_FROM_CART_FAILURE = "REMOVE_FROM_CART_FAILURE";

// Clear cart
export const CLEAR_CART_REQUEST = "CLEAR_CART_REQUEST";
export const CLEAR_CART_SUCCESS = "CLEAR_CART_SUCCESS";
export const CLEAR_CART_FAILURE = "CLEAR_CART_FAILURE";

// Cart count
export const GET_CART_COUNT_REQUEST = "GET_CART_COUNT_REQUEST";
export const GET_CART_COUNT_SUCCESS = "GET_CART_COUNT_SUCCESS";
export const GET_CART_COUNT_FAILURE = "GET_CART_COUNT_FAILURE";

// Merge cart
export const MERGE_CART_REQUEST = "MERGE_CART_REQUEST";
export const MERGE_CART_SUCCESS = "MERGE_CART_SUCCESS";
export const MERGE_CART_FAILURE = "MERGE_CART_FAILURE";

// Coupon
export const APPLY_COUPON_REQUEST = "APPLY_COUPON_REQUEST";
export const APPLY_COUPON_SUCCESS = "APPLY_COUPON_SUCCESS";
export const APPLY_COUPON_FAILURE = "APPLY_COUPON_FAILURE";
export const REMOVE_COUPON = "REMOVE_COUPON";

// Shipping
export const CALCULATE_SHIPPING_REQUEST = "CALCULATE_SHIPPING_REQUEST";
export const CALCULATE_SHIPPING_SUCCESS = "CALCULATE_SHIPPING_SUCCESS";
export const CALCULATE_SHIPPING_FAILURE = "CALCULATE_SHIPPING_FAILURE";

// Local actions
export const SET_CART_ITEM_QUANTITY = "SET_CART_ITEM_QUANTITY";
export const SET_LOADING_ITEM = "SET_LOADING_ITEM";
export const RESET_CART_ERROR = "RESET_CART_ERROR";
