export const PRODUCT_ADD_REQUEST = "PRODUCT_ADD_REQUEST";
export const PRODUCT_ADD_SUCCESS = "PRODUCT_ADD_SUCCESS";
export const PRODUCT_ADD_FAIL = "PRODUCT_ADD_FAIL";

export const PRODUCT_FETCH_REQUEST = "PRODUCT_FETCH_REQUEST";
export const PRODUCT_FETCH_SUCCESS = "PRODUCT_FETCH_SUCCESS";
export const PRODUCT_FETCH_FAIL = "PRODUCT_FETCH_FAIL";

export const FETCH_PRODUCT_BY_ID_REQUEST = "FETCH_PRODUCT_BY_ID_REQUEST";
export const FETCH_PRODUCT_BY_ID_SUCCESS = "FETCH_PRODUCT_BY_ID_SUCCESS";
export const FETCH_PRODUCT_BY_ID_FAIL = "FETCH_PRODUCT_BY_ID_FAIL";

export const UPDATE_PRODUCT_REQUEST = "UPDATE_PRODUCT_REQUEST";
export const UPDATE_PRODUCT_SUCCESS = "UPDATE_PRODUCT_SUCCESS";
export const UPDATE_PRODUCT_FAIL = "UPDATE_PRODUCT_FAIL";

export const SOFT_DELETE_PRODUCT_REQUEST = "SOFT_DELETE_PRODUCT_REQUEST";
export const SOFT_DELETE_PRODUCT_SUCCESS = "SOFT_DELETE_PRODUCT_SUCCESS";
export const SOFT_DELETE_PRODUCT_FAIL = "SOFT_DELETE_PRODUCT_FAIL";

export const FETCH_SOFT_DELETE_PRODUCT_REQUEST =
  "FETCH_SOFT_DELETE_PRODUCT_REQUEST";
export const FETCH_SOFT_DELETE_PRODUCT_SUCCESS =
  "FETCH_SOFT_DELETE_PRODUCT_SUCCESS";
export const FETCH_SOFT_DELETE_PRODUCT_FAIL = "FETCH_SOFT_DELETE_PRODUCT_FAIL";

export const HARD_DELETE_PRODUCT_REQUEST = "HARD_DELETE_PRODUCT_REQUEST";
export const HARD_DELETE_PRODUCT_SUCCESS = "HARD_DELETE_PRODUCT_SUCCESS";
export const HARD_DELETE_PRODUCT_FAIL = "HARD_DELETE_PRODUCT_FAIL";

export const RESTORE_PRODUCT_REQUEST = "RESTORE_PRODUCT_REQUEST";
export const RESTORE_PRODUCT_SUCCESS = "RESTORE_PRODUCT_SUCCESS";
export const RESTORE_PRODUCT_FAIL = "RESTORE_PRODUCT_FAIL";
