export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";

export const USER_LOGOUT = "USER_LOGOUT";

export const USER_PROFILE_REQUEST = "USER_PROFILE_REQUEST";
export const USER_PROFILE_SUCCESS = "USER_PROFILE_SUCCESS";
export const USER_PROFILE_FAIL = "USER_PROFILE_FAIL";

export const FETCH_USER_REQUEST = "FETCH_USER_REQUEST";
export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS";
export const FETCH_USER_FAIL = "FETCH_USER_FAIL";

export const FETCH_USER_SOFT_DELETED_REQUEST =
  "FETCH_USER_SOFT_DELETED_REQUEST";
export const FETCH_USER_SOFT_DELETED_SUCCESS =
  "FETCH_USER_SOFT_DELETED_SUCCESS";
export const FETCH_USER_SOFT_DELETED_FAIL = "FETCH_USER_SOFT_DELETED_FAIL";

export const CREATE_USER_REQUEST = "CREATE_USER_REQUEST";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const CREATE_USER_FAIL = "CREATE_USER_FAIL";

export const UPDATE_USER_REQUEST = "UPDATE_USER_REQUEST";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_FAIL = "UPDATE_USER_FAIL";

export const SOFT_DELETE_USER_REQUEST = "SOFT_DELETE_USER_REQUEST";
export const SOFT_DELETE_USER_SUCCESS = "SOFT_DELETE_USER_SUCCESS";
export const SOFT_DELETE_USER_FAIL = "SOFT_DELETE_USER_FAIL";

export const HARD_DELETE_USER_REQUEST = "HARD_DELETE_USER_REQUEST";
export const HARD_DELETE_USER_SUCCESS = "HARD_DELETE_USER_SUCCESS";
export const HARD_DELETE_USER_FAIL = "HARD_DELETE_USER_FAIL";

export const RESTORE_USER_REQUEST = "RESTORE_USER_REQUEST";
export const RESTORE_USER_SUCCESS = "RESTORE_USER_SUCCESS";
export const RESTORE_USER_FAIL = "RESTORE_USER_FAIL";
